#!/usr/bin/env python3
"""Load cached CompanyProfile → transform → write data.js for frontend preview.

Usage (from RADAR/radar/backend/):
    source .venv/bin/activate
    python3 scripts/preview_understand.py makipeople.com

Then in another terminal:
    cd RADAR/radar/frontend-prototype
    python3 -m http.server 8080
    open http://localhost:8080
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

load_dotenv()

from models.company import CompanyProfile
from models.pipeline import PipelineRun, PipelineStatus
from pipeline.transform import pipeline_run_to_radar_output

# Paths: scripts/ → backend/ → radar/ → cache/ and frontend-prototype/
_RADAR_DIR = Path(__file__).resolve().parents[2]  # RADAR/radar/
CACHE_DIR = _RADAR_DIR / "cache"
FRONTEND = _RADAR_DIR / "frontend-prototype"


def main(domain: str) -> None:
    cache_file = CACHE_DIR / f"understand_{domain}.json"
    if not cache_file.exists():
        print(f"✗  Cache file not found: {cache_file}")
        print(f"   Run first: python3 -m pipeline.understand {domain}")
        sys.exit(1)

    profile = CompanyProfile.model_validate_json(cache_file.read_text())
    print(f"✓  Loaded  : {profile.name} ({domain})")
    print(f"   HQ      : {profile.hq.city if profile.hq else '?'}, {profile.hq.country if profile.hq else '?'}")
    print(f"   Funding : {profile.funding_stage or '?'}")
    print(f"   Investors: {len(profile.notable_investors or [])}")
    print(f"   Customers: {len(profile.notable_customers or [])}")

    now = datetime.now(timezone.utc).isoformat()
    run = PipelineRun(
        id="preview",
        company_domain=domain,
        status=PipelineStatus.COMPLETED,
        created_at=now,
        completed_at=now,
        company_profile=profile,
        competitors=[],  # UNDERSTAND-only preview — no competitors
    )

    radar_output = pipeline_run_to_radar_output(run)
    radar_json = radar_output.model_dump(by_alias=True, mode="json", exclude_none=False)

    # Escape </ to prevent </script> injection breaking the page when
    # data contains text like "</script>" (press release snippets, headlines).
    payload = json.dumps(radar_json, indent=2, ensure_ascii=False).replace("</", "<\\/")

    data_js = FRONTEND / "data.js"
    data_js.write_text(
        "// Auto-generated by scripts/preview_understand.py — DO NOT EDIT\n"
        f"// Domain: {domain} — {now}\n"
        f"window.RADAR_DATA = {payload};\n",
        encoding="utf-8",
    )
    print(f"\n✓  Written : {data_js}")
    print()
    print("─── Next steps ─────────────────────────────────────")
    print(f"  cd {FRONTEND}")
    print("  python3 -m http.server 8080")
    print("  open http://localhost:8080")
    print("────────────────────────────────────────────────────")
    print()
    print("Expected in Overview tab:")
    print(f"  Name      : {profile.name}")
    print(f"  HQ        : {profile.hq.city if profile.hq else '?'}, {profile.hq.country if profile.hq else '?'}")
    print(f"  Founded   : {profile.founded_year or '?'}")
    print(f"  Employees : {profile.employees.value if profile.employees else '?'}")
    if profile.funding and profile.funding.total_raised_eur:
        print(f"  Funding   : {profile.funding_stage} — €{profile.funding.total_raised_eur.value:,}")
    print(f"  Investors : {', '.join(inv.name for inv in (profile.notable_investors or [])[:4])}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 scripts/preview_understand.py <domain>")
        sys.exit(1)
    main(sys.argv[1].strip().lower())
