"""Serialize a RadarOutput to the data.js format consumed by the Radar frontend.

Usage (CLI):
    python -m utils.data_js <pipeline_run.json> <output_data.js>

Usage (Python):
    from pipeline.transform import pipeline_run_to_radar_output
    from utils.data_js import generate_data_js

    run = PipelineRun.model_validate_json(Path("cache.json").read_text())
    generate_data_js(pipeline_run_to_radar_output(run), "frontend/data.js")
"""
from __future__ import annotations

import json
from pathlib import Path

from models.radar_output import RadarOutput


def generate_data_js(data: RadarOutput, output_path: str | Path) -> None:
    raw = data.model_dump(by_alias=True, mode="json", exclude_none=True)

    # allCompanies: subject first, competitors sorted by similarity desc
    subject = raw["subject"]
    competitors_sorted = sorted(
        raw["competitors"],
        key=lambda c: c.get("similarity") or 0.0,
        reverse=True,
    )
    all_companies = [subject, *competitors_sorted]

    main_json = json.dumps(raw, indent=2, ensure_ascii=False)
    all_companies_json = json.dumps(all_companies, indent=2, ensure_ascii=False)

    js = (
        "// Auto-generated by utils/data_js.py — do not edit manually.\n"
        f"window.RADAR_DATA = {main_json};\n\n"
        f"window.RADAR_DATA.allCompanies = {all_companies_json};\n"
    )

    Path(output_path).write_text(js, encoding="utf-8")


if __name__ == "__main__":
    import sys

    from models.pipeline import PipelineRun
    from pipeline.transform import pipeline_run_to_radar_output

    if len(sys.argv) < 3:
        print(
            "Usage: python -m utils.data_js <pipeline_run.json> <output_data.js>",
            file=sys.stderr,
        )
        sys.exit(1)

    pipeline_json = Path(sys.argv[1]).read_text(encoding="utf-8")
    run = PipelineRun.model_validate_json(pipeline_json)
    radar_output = pipeline_run_to_radar_output(run)
    generate_data_js(radar_output, sys.argv[2])
    print(f"Written → {sys.argv[2]}")
