// Auto-generated by scripts/preview_understand.py — DO NOT EDIT
// Domain: makipeople.com — 2026-05-26T18:26:14.181588+00:00
window.RADAR_DATA = {
  "query": {
    "url": "makipeople.com",
    "name": "Maki People",
    "scannedAt": "2026-05-26T18:26:14.181588+00:00",
    "durationMs": 0,
    "sourcesScanned": 100
  },
  "subject": {
    "id": "maki_people",
    "name": "Maki People",
    "domain": "makipeople.com",
    "tagline": "Maki People provides AI-powered hiring workflow automation that runs end-to-end on top of existing ATS systems. The platform uses five autonomous AI agents (Shiro, Mochi, Ken, Kumi, Tomo) to handle intake, screening, assessment, interviews, and hire recommendations with predictive science validation.",
    "category": "HR Technology",
    "subCategory": "AI hiring workflow automation platform with science-grade validation",
    "hq": "Paris, France",
    "hqCoords": [
      48.8534951,
      2.3483915
    ],
    "offices": [
      "Paris"
    ],
    "founded": 2021,
    "employees": 122,
    "employeeGrowth": 0.0,
    "funding": {
      "total": 33800000.0,
      "lastRound": "Series A",
      "lastRoundAt": "2025-01-15"
    },
    "investors": [
      "Blossom Capital",
      "DST Global",
      "Frst Capital",
      "Global Founders Capital",
      "Picus Capital",
      "Secret Fund",
      "Kima Ventures",
      "Founders Future"
    ],
    "pricing": {
      "model": "Custom",
      "startsAt": 0.0,
      "mention": "Contact sales"
    },
    "arr": null,
    "customers": null,
    "avgContract": null,
    "notable": [
      "Raised €27.8M Series A in January 2025",
      "Hiring 60+ roles in 2025",
      "Expansion focus on U.S. market with CEO relocating to New York City",
      "Platform integrated with 30+ ATS systems",
      "Serving 50+ markets globally with 80% automation of screening and interviewing processes"
    ],
    "notable_customers": [
      {
        "name": "Deloitte",
        "domain": "deloitte.com"
      },
      {
        "name": "Nespresso",
        "domain": "nespresso.com"
      },
      {
        "name": "Capgemini",
        "domain": "capgemini.com"
      },
      {
        "name": "Forvis Mazars",
        "domain": "forvismazars.com"
      },
      {
        "name": "H&M",
        "domain": "hm.com"
      },
      {
        "name": "BNP Paribas",
        "domain": "bnpparibas.com"
      },
      {
        "name": "EY",
        "domain": "ey.com"
      },
      {
        "name": "Amazon",
        "domain": "amazon.com"
      },
      {
        "name": "PwC",
        "domain": "pwc.com"
      },
      {
        "name": "Delta Airlines",
        "domain": "delta.com"
      },
      {
        "name": "BD",
        "domain": "bd.com"
      },
      {
        "name": "FIFA",
        "domain": "fifa.com"
      }
    ],
    "notable_investors": [
      {
        "name": "Blossom Capital",
        "domain": "blossomcap.com"
      },
      {
        "name": "DST Global",
        "domain": "dst-global.com"
      },
      {
        "name": "Frst Capital",
        "domain": null
      },
      {
        "name": "Global Founders Capital",
        "domain": "globalfounders.vc"
      },
      {
        "name": "Picus Capital",
        "domain": null
      },
      {
        "name": "Secret Fund",
        "domain": null
      },
      {
        "name": "Kima Ventures",
        "domain": "kimaventures.com"
      },
      {
        "name": "Founders Future",
        "domain": null
      }
    ],
    "isSubject": true,
    "similarity": null,
    "threat": null
  },
  "competitors": [],
  "features": [],
  "capabilities": {
    "maki_people": []
  },
  "pricing": {
    "maki_people": []
  },
  "funding": {
    "maki_people": [
      {
        "y": 2021,
        "q": 4,
        "amt": 6.0,
        "round": "Seed"
      },
      {
        "y": 2025,
        "q": 1,
        "amt": 27.8,
        "round": "Series A"
      }
    ]
  },
  "radar": {
    "axes": [
      "Breadth",
      "Depth",
      "Global",
      "Developer",
      "Pricing",
      "Trust"
    ],
    "scores": {
      "maki_people": [
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0
      ]
    },
    "defs": {
      "Breadth": "Breadth of product surface (modules, use-cases)",
      "Depth": "Depth within core payment workflows",
      "Global": "Geographic and currency coverage",
      "Developer": "API quality, docs, embedded SDKs",
      "Pricing": "Price-competitiveness for SMB/mid-market",
      "Trust": "Compliance, brand and customer logos"
    }
  }
};
