// Auto-generated by utils/eval_to_data_js.py — Positioning demo data.
window.RADAR_DATA = {
  "query": {
    "url": "https://",
    "name": "TestGorilla",
    "scannedAt": "2026-05-27T07:07:30.251969+00:00",
    "durationMs": 0,
    "sourcesScanned": 86
  },
  "subject": {
    "id": "testgorilla",
    "name": "TestGorilla",
    "domain": "",
    "tagline": "Hire for real skills, IGNORE AI resumes. [TestGorilla: AI-Powered Talent Sourcing & Skills Assessments](https://www.testgorilla.com)",
    "category": "HR Technology",
    "subCategory": "Pre-employment testing software",
    "hq": "Amsterdam, Netherlands",
    "hqCoords": [
      52.3676,
      4.9041
    ],
    "offices": [
      "Amsterdam"
    ],
    "founded": 2020,
    "employees": 337,
    "employeeGrowth": 0.24,
    "funding": {
      "total": 74704000.0,
      "lastRound": "Series A",
      "lastRoundAt": "2022-06-13",
      "status": "enriched",
      "rounds": [
        {
          "round": "Pre-Seed",
          "date": "2020-01-01",
          "amountEur": 1104000.0
        },
        {
          "round": "Seed",
          "date": "2021-07-01",
          "amountEur": 9200000.0
        },
        {
          "round": "Series A",
          "date": "2022-06-13",
          "amountEur": 64400000.0
        }
      ],
      "totalRaisedEur": 74704000.0
    },
    "fundingRounds": [
      {
        "round": "Pre-Seed",
        "date": "2020-01-01",
        "amountEur": 1104000.0
      },
      {
        "round": "Seed",
        "date": "2021-07-01",
        "amountEur": 9200000.0
      },
      {
        "round": "Series A",
        "date": "2022-06-13",
        "amountEur": 64400000.0
      }
    ],
    "fundingStage": "Series A",
    "investors": [
      "Atomico",
      "Balderton Capital",
      "Notion Capital",
      "Partech",
      "Next Play Ventures"
    ],
    "notable_investors": [
      {
        "name": "Atomico"
      },
      {
        "name": "Balderton Capital"
      },
      {
        "name": "Notion Capital"
      },
      {
        "name": "Partech"
      },
      {
        "name": "Next Play Ventures"
      }
    ],
    "notable_customers": [
      {
        "name": "Dyninno Group",
        "segment": "Mixed",
        "evidence": "Increased recruitment productivity by 400% and screening efficiency by 4x using TestGorilla. [Dyninno Group improves candidate screening rate and increases recruitment productivity by 400% using TestGorilla](https://www.testgorilla.com/case-studies/dyninno-group-increases-recruitment-productivity-by-400-percent/)",
        "industry": "Travel, Finance, Entertainment, and Technology"
      },
      {
        "name": "Revolut",
        "segment": "Enterprise",
        "evidence": "Reported hiring 40% faster after implementing TestGorilla's assessment platform. [TestGorilla case studies - Helping companies hire the best talent](https://www.testgorilla.com/case-studies/revolut-improves-time-to-hire-by-40-using-testgorilla/)",
        "industry": "Financial Services"
      },
      {
        "name": "Penbrothers",
        "segment": "Enterprise",
        "evidence": "Used TestGorilla to reduce early attrition and improve candidate experience. [TestGorilla case studies - Helping companies hire the best talent](https://www.testgorilla.com/case-studies/penbrothers-humanises-global-hiring/)",
        "industry": "Global Talent Outsourcing"
      },
      {
        "name": "Orbit Technologies",
        "segment": "Enterprise",
        "evidence": "Improved new hire retention by 50% and reduced bias using TestGorilla. [TestGorilla case studies - Helping companies hire the best talent](https://www.testgorilla.com/case-studies/orbit-technologies-reduces-new-hire-attrition-rates/)",
        "industry": "Engineering"
      },
      {
        "name": "Lima Innovation Lab (LILAB)",
        "segment": "PME",
        "evidence": "Boosted new employee retention up to 90% using the platform. [TestGorilla case studies - Helping companies hire the best talent](https://www.testgorilla.com/case-studies/lilab-boost-new-employee-retention-up-to-90/)",
        "industry": "Software"
      }
    ],
    "key_people": [
      {
        "name": "Wouter Durville",
        "role": "CEO and Co-Founder",
        "linkedin": "linkedin.com/in/wouter-durville",
        "background": "CEO and Co-Founder of TestGorilla. [Wouter Durville](https://www.linkedin.com/in/wouter-durville)"
      },
      {
        "name": "Otto Verhage",
        "role": "COO and Co-Founder",
        "linkedin": "linkedin.com/in/otto-verhage",
        "background": "COO and Co-Founder of TestGorilla. [Otto Verhage - COO / Co-Founder at TestGorilla](https://nl.linkedin.com/in/otto-verhage)"
      },
      {
        "name": "Olive Turon",
        "role": "Head of People and Culture",
        "linkedin": "linkedin.com/in/olive-turon",
        "background": "Head of People and Culture at TestGorilla. [Olive Turon - LinkedIn](https://www.linkedin.com/in/olive-turon)"
      },
      {
        "name": "Megan Bourdages",
        "role": "VP of Sales",
        "linkedin": "linkedin.com/in/meganbourdages",
        "background": "VP of Sales at TestGorilla, leading the global sales organization. [Megan Bourdages - AMB International | LinkedIn](https://www.linkedin.com/in/meganbourdages/)"
      },
      {
        "name": "Romina da Costa",
        "role": "Product Director (IP Development)",
        "linkedin": "linkedin.com/in/rominadacosta",
        "background": "Product Director (IP Development) and Director of Talent and Assessment Science at TestGorilla. [Romina Da Costa - LinkedIn](https://www.linkedin.com/in/rominadacosta)"
      }
    ],
    "customers": 60000,
    "arr": 33304000.0,
    "avgContract": null,
    "business_model": "B2B",
    "gtm_motion": "product-led",
    "target_segment": "Mixed",
    "geo_coverage": "Global",
    "acquisition": {
      "acquired": false,
      "acquirer": null,
      "year": null,
      "sourceUrl": null
    },
    "recentNews": [
      {
        "date": "2026-05-06",
        "headline": "59% of Organizations Made a 'Bad AI Hire' in the Past Year, New TestGorilla Research Reveals",
        "source_url": "https://www.afp.com/en/infos/59-organizations-made-bad-ai-hire-past-year-new-testgorilla-research-reveals"
      },
      {
        "date": "2026-03-04",
        "headline": "TestGorilla launched a new suite of AI Readiness and AI Fluency assessments and simulation tests",
        "source_url": "https://tracxn.com/d/companies/testgorilla/__R2kvquwDSxYmt-AXwK9Qt8l_ReBLCwOIrxWBihbXqPo"
      },
      {
        "date": "2026-03-03",
        "headline": "TestGorilla Launches New AI Readiness and AI Fluency Assessments",
        "source_url": "https://lifestyle.pierrecountry.com/story/91873/testgorilla-launches-new-ai-readiness-and-ai-fluency-assessments-to-help-companies-hire-for-the-skills-that-matter-now/"
      },
      {
        "date": "2026-01-01",
        "headline": "TestGorilla launched five new simulation tests designed to mirror high-pressure scenarios for roles in Sales and Customer Success",
        "source_url": "https://support.testgorilla.com/hc/en-us/articles/46569751180699-Release-notes-December-2025-and-January-2026"
      },
      {
        "date": "2025-10-07",
        "headline": "TestGorilla introduced AI Video Interviews for skills-based screening",
        "source_url": "https://tracxn.com/d/companies/testgorilla/__R2kvquwDSxYmt-AXwK9Qt8l_ReBLCwOIrxWBihbXqPo"
      }
    ],
    "growthSignals": [
      "TestGorilla's revenue reached $36.2M ARR in 2025, with the company's valuation reported at $108.6M. [TestGorilla Revenue 2025: $36.2M ARR, $108.6M Valuation](https://getlatka.com/companies/testgorilla.com)",
      "As of March 2026, TestGorilla reports that more than 60,000 organizations use the platform, which assesses approximately 7 million candidates annually. [TestGorilla Launches New AI Readiness and AI Fluency Assessments - Morningstar](https://www.morningstar.com/news/business-wire/20260303398545/testgorilla-launches-new-ai-readiness-and-ai-fluency-assessments-to-help-companies-hire-for-the-skills-that-matter-now)",
      "TestGorilla grew its employee count by 24% last year. [TestGorilla: Revenue, Competitors, Alternatives](https://growjo.com/company/TestGorilla)"
    ],
    "top3Features": [
      "Library of 350+ scientifically validated skills tests",
      "AI video interviews with auto-scoring",
      "AI resume scoring against job descriptions"
    ],
    "targetVerticals": [
      "BPO",
      "Finance",
      "IT",
      "Sales"
    ],
    "isSubject": true,
    "similarity": 1.0,
    "threat": "high",
    "pricing": {
      "model": "Custom",
      "starts_at": 0,
      "mention": "Contact sales"
    }
  },
  "competitors": [
    {
      "id": "hirevue",
      "name": "HireVue",
      "domain": "hirevue.com",
      "tagline": "HireVue is where hiring happens.",
      "category": "HR Technology",
      "subCategory": "Hiring Platform",
      "hq": "Salt Lake City, United States",
      "hqCoords": [
        40.7608,
        -111.891
      ],
      "offices": [
        "Salt Lake City"
      ],
      "founded": 2004,
      "employees": 331,
      "employeeGrowth": 0.08,
      "funding": {
        "total": 85928000.0,
        "lastRound": "Series E",
        "lastRoundAt": "2015-06-02",
        "status": "enriched",
        "rounds": [
          {
            "round": "Series A",
            "date": "2008-02-10",
            "amountEur": 920000.0
          },
          {
            "round": "Series B",
            "date": "2010-07-27",
            "amountEur": 4600000.0
          },
          {
            "round": "Series E",
            "date": "2015-06-02",
            "amountEur": null
          }
        ],
        "totalRaisedEur": 85928000.0
      },
      "fundingRounds": [
        {
          "round": "Series A",
          "date": "2008-02-10",
          "amountEur": 920000.0
        },
        {
          "round": "Series B",
          "date": "2010-07-27",
          "amountEur": 4600000.0
        },
        {
          "round": "Series E",
          "date": "2015-06-02",
          "amountEur": null
        }
      ],
      "fundingStage": "Acquired",
      "investors": [
        "The Carlyle Group",
        "TCV",
        "Sequoia Capital",
        "Granite Ventures"
      ],
      "notable_investors": [
        {
          "name": "The Carlyle Group",
          "domain": "carlyle.com"
        },
        {
          "name": "TCV",
          "domain": "tcv.com"
        },
        {
          "name": "Sequoia Capital"
        },
        {
          "name": "Granite Ventures"
        }
      ],
      "notable_customers": [
        {
          "name": "Unilever",
          "domain": "unilever.com",
          "segment": "Enterprise",
          "evidence": "https://www.bestpractice.ai/ai-case-study-best-practice/unilever_saved_over_50,000_hours_in_candidate_interview_time_and_delivered_over_%C2%A31m_annual_savings_and_improved_candidate_diversity_with_machine_analysis_of_video-based_interviewing.",
          "industry": "Consumer Products"
        },
        {
          "name": "Delta Air Lines",
          "domain": "delta.com",
          "segment": "Enterprise",
          "evidence": "https://www.hirevue.com/case-studies/customer-videos/page/7",
          "industry": "Travel and Leisure"
        },
        {
          "name": "Walmart",
          "domain": "walmart.com",
          "segment": "Enterprise",
          "evidence": "https://www.hirevue.com/blog/hiring/high-volume-recruiting-success-case-studies",
          "industry": "Retail"
        },
        {
          "name": "IKEA",
          "domain": "ikea.com",
          "segment": "Enterprise",
          "evidence": "https://www.hirevue.com/case-studies",
          "industry": "Retail"
        },
        {
          "name": "Emirates NBD",
          "domain": "emiratesnbd.com",
          "segment": "Enterprise",
          "evidence": "https://www.hirevue.com/case-studies",
          "industry": "Banking"
        }
      ],
      "key_people": [
        {
          "name": "Jeremy Friedman",
          "background": "Chief Executive Officer (CEO) at HireVue, appointed in January 2024, recently leading the acquisition of Hireguide.",
          "current_role": "Chief Executive Officer (CEO)",
          "linkedin_url": "https://www.linkedin.com/in/jnfriedman"
        },
        {
          "name": "Alberto Silveira",
          "background": "Chief Technology Officer (CTO) at HireVue focused on breakthrough innovations and scaling product development.",
          "current_role": "Chief Technology Officer (CTO)",
          "linkedin_url": "https://www.linkedin.com/in/asilveira/"
        },
        {
          "name": "Walker Ellis",
          "background": "Chief Revenue Officer (CRO) at HireVue responsible for the company's revenue operations and strategic growth.",
          "current_role": "Chief Revenue Officer (CRO)",
          "linkedin_url": "https://www.linkedin.com/in/walker-ellis-26b20716/"
        },
        {
          "name": "Marcy Daniel",
          "background": "Chief Product Officer (CPO) at HireVue leading the product vision and development for the AI-driven talent platform.",
          "current_role": "Chief Product Officer (CPO)",
          "linkedin_url": "https://www.linkedin.com/in/marcyldaniel/"
        },
        {
          "name": "Sibyl McCarley",
          "background": "Chief People Officer at HireVue, having started the role on August 1, 2024.",
          "current_role": "Chief People Officer",
          "linkedin_url": "https://www.linkedin.com/in/sibyl-mccarley-7161543"
        }
      ],
      "customers": 1150,
      "arr": 76176000.0,
      "avgContract": 45866.6,
      "business_model": "B2B",
      "gtm_motion": "sales-led",
      "target_segment": "Enterprise",
      "geo_coverage": "Global",
      "acquisition": {
        "acquired": true,
        "acquirer": "The Carlyle Group",
        "year": 2019,
        "sourceUrl": "https://www.prnewswire.com/news-releases/hirevue-announces-close-of-transaction-with-the-carlyle-group-300937878.html"
      },
      "recentNews": [
        {
          "date": "2026-03-10",
          "headline": "HireVue announced the acquisition of the technology behind Hireguide",
          "source_url": "https://www.globenewswire.com/search/organization/Hirevue"
        },
        {
          "date": "2026-02-19",
          "headline": "HireVue launched 'Assessment Builder'",
          "source_url": "https://www.staffingindustry.com/news/global-daily-news/hirevue-acquires-hireguide"
        },
        {
          "date": "2026-01-13",
          "headline": "HireVue joined the Workday AI Agent Partner Network",
          "source_url": "https://www.hirevue.com/press-release"
        },
        {
          "date": "2025-10-08",
          "headline": "HireVue announced the launch of 'Interview Insights'",
          "source_url": "https://www.hirevue.com/press-release/hirevue-announces-interview-insights-expanding-its-innovation-in-skill-validation"
        },
        {
          "date": "2025-08-12",
          "headline": "HireVue launched 'Hirevue Talent Engagement'",
          "source_url": "https://www.globenewswire.com/search/organization/Hirevue"
        }
      ],
      "growthSignals": [
        "Acquired Hireguide in March 2026 to accelerate its AI strategy and strengthen conversational hiring technology.",
        "Joined the Workday AI Agent Partner Network in January 2026 to accelerate the shift toward skills-based hiring.",
        "Expanded its product suite with the launch of Assessment Builder and Interview Insights in late 2025 and early 2026."
      ],
      "top3Features": [
        "Video Interviewing",
        "Assessments",
        "Conversational AI"
      ],
      "targetVerticals": [
        "Retail",
        "Finance",
        "Software",
        "Pharmaceuticals",
        "Public Sector"
      ],
      "isSubject": false,
      "similarity": 0.84,
      "threat": "high",
      "pricing": {
        "model": "Custom",
        "starts_at": 0,
        "mention": "Contact sales"
      }
    },
    {
      "id": "paradox",
      "name": "Paradox",
      "domain": "",
      "tagline": "Conversational hiring software that gets work done for you. [Conversational hiring software that gets work done for you — Paradox](https://www.paradox.ai/)",
      "category": "HR Technology",
      "subCategory": "Conversational AI",
      "hq": "Scottsdale, US",
      "hqCoords": [
        33.4942,
        -111.9261
      ],
      "offices": [
        "Scottsdale"
      ],
      "founded": 2016,
      "employees": 429,
      "employeeGrowth": 0.0,
      "funding": {
        "total": 233183200.0,
        "lastRound": "Series C",
        "lastRoundAt": "2021-12-27",
        "status": "enriched",
        "rounds": [
          {
            "round": "Series A",
            "date": "2019-02-28",
            "amountEur": 12236000.0
          },
          {
            "round": "Series B",
            "date": "2020-05-11",
            "amountEur": 36800000.0
          },
          {
            "round": "Series C",
            "date": "2021-12-27",
            "amountEur": 184000000.0
          }
        ],
        "totalRaisedEur": 233183200.0
      },
      "fundingRounds": [
        {
          "round": "Series A",
          "date": "2019-02-28",
          "amountEur": 12236000.0
        },
        {
          "round": "Series B",
          "date": "2020-05-11",
          "amountEur": 36800000.0
        },
        {
          "round": "Series C",
          "date": "2021-12-27",
          "amountEur": 184000000.0
        }
      ],
      "fundingStage": "Acquired",
      "investors": [
        "Brighton Park Capital",
        "Stripes",
        "Sapphire Ventures",
        "Thoma Bravo",
        "Workday Ventures"
      ],
      "notable_investors": [
        {
          "name": "Brighton Park Capital"
        },
        {
          "name": "Stripes"
        },
        {
          "name": "Sapphire Ventures"
        },
        {
          "name": "Thoma Bravo"
        },
        {
          "name": "Workday Ventures"
        }
      ],
      "notable_customers": [
        {
          "name": "Compass Group",
          "segment": "Enterprise",
          "evidence": "Hiring 160,000 workers a year with a recruiting team of 20 [Hiring 160,000 workers a year with a recruiting team of 20.](https://www.paradox.ai/case-studies/compass-group)",
          "industry": "Food & Facilities"
        },
        {
          "name": "7-Eleven",
          "segment": "Enterprise",
          "evidence": "Uses Paradox to schedule 85% of applicants within the hour, saving store managers 40,000 hours per week [Paradox named to its fifth consecutive Inc. 5000 list — ranked as #X among HR technology companies. — Paradox](https://www.paradox.ai/news/paradox-named-to-its-fifth-consecutive-inc-5000-list-among-the-fastest-growing-hr-technology-companies).",
          "industry": "Retail"
        },
        {
          "name": "General Motors",
          "segment": "Enterprise",
          "evidence": "Saved more than $2 million in operational recruiting costs by leveraging Paradox automation [Paradox Named to Third Consecutive Inc. 5000 List — Growing by More than 720% Since 2020 — Paradox](https://www.paradox.ai/news/paradox-named-to-third-consecutive-inc-5000-list-growing-by-more-than-720-since-2020).",
          "industry": "Automotive"
        },
        {
          "name": "Sodexo",
          "segment": "Enterprise",
          "evidence": "Hired more than 40,000 people in seven months using Paradox's Conversational ATS [Decreasing time to hire by 60% with recruiting automation.](https://www.paradox.ai/case-studies/sodexo).",
          "industry": "Food & Facilities"
        },
        {
          "name": "Nestlé",
          "segment": "Enterprise",
          "evidence": "Utilizes Paradox to automate nearly 8,000 hours of recruiting work annually [Increasing interviews by 600% with recruiting automation.](https://www.paradox.ai/case-studies/nestle).",
          "industry": "Food & Beverage"
        }
      ],
      "key_people": [
        {
          "name": "Adam Godson",
          "role": "Chief Executive Officer",
          "linkedin": "linkedin.com/in/adamgodson",
          "background": "Adam Godson is the Chief Executive Officer (CEO) of Paradox and the General Manager of Paradox at Workday [Adam Godson - Workday | LinkedIn](https://www.linkedin.com/in/adamgodson/)."
        },
        {
          "name": "Stephanie King",
          "role": "Chief Legal Officer",
          "linkedin": "linkedin.com/in/stephanie-king-37346366",
          "background": "Stephanie King is the Chief Legal Officer at Paradox [Stephanie King - Chief Legal Officer](https://www.linkedin.com/in/stephanie-king-37346366/)."
        },
        {
          "name": "Alon Slutzky",
          "role": "VP of Engineering",
          "linkedin": "linkedin.com/in/slutzky",
          "background": "Alon Slutzky is the VP of Engineering at Paradox [Alon Slutzky - Workday | LinkedIn](https://www.linkedin.com/in/slutzky/)."
        },
        {
          "name": "Joshua Secrest",
          "role": "Vice President, Marketing & Client Advocacy",
          "linkedin": "linkedin.com/in/joshua-secrest-44b0042",
          "background": "Joshua Secrest is the Vice President, Marketing & Client Advocacy at Paradox [Joshua Secrest - Vice President, Marketing & Client Advocacy - Paradox | LinkedIn](https://www.linkedin.com/in/joshua-secrest-44b0042/)."
        },
        {
          "name": "Tri LE",
          "role": "VP & Head of Engineering, Vietnam",
          "linkedin": "linkedin.com/in/lehuutri",
          "background": "Tri LE is the VP & Head of Engineering, Vietnam at Paradox [Tri LE - VP & Head of Engineering, Vietnam - Paradox | LinkedIn](https://www.linkedin.com/in/lehuutri/?_l=en)."
        }
      ],
      "customers": null,
      "arr": 106536000.0,
      "avgContract": null,
      "business_model": "B2B",
      "gtm_motion": "sales-led",
      "target_segment": "Enterprise",
      "geo_coverage": "Global",
      "acquisition": {
        "acquired": true,
        "acquirer": "Workday",
        "year": 2025,
        "sourceUrl": "https://newsroom.workday.com/2025-10-01-Workday-Completes-Acquisition-of-Paradox"
      },
      "recentNews": [
        {
          "date": "2025-06-03",
          "headline": "Workday Announces New AI Agent Partner Network and Agent Gateway to Power the Next Generation of Human and Digital Workforces",
          "source_url": "https://newsroom.workday.com/2025-06-03-Workday-Announces-New-AI-Agent-Partner-Network-and-Agent-Gateway-to-Power-the-Next-Generation-of-Human-and-Digital-Workforces"
        },
        {
          "date": "2025-08-21",
          "headline": "Workday Signs Definitive Agreement to Acquire Paradox, the AI Company Redefining the Frontline Candidate Experience",
          "source_url": "https://www.prnewswire.com/news-releases/workday-signs-definitive-agreement-to-acquire-paradox-the-ai-company-redefining-the-frontline-candidate-experience-302536210.html"
        },
        {
          "date": "2025-08-01",
          "headline": "Paradox's New Immersive Job Preview Named 2025 Top HR Product of the Year by HR Executive",
          "source_url": "https://www.prnewswire.com/news-releases/paradoxs-new-immersive-job-preview-named-2025-top-hr-product-of-the-year-by-hr-executive-302526075.html"
        },
        {
          "date": "2025-10-01",
          "headline": "Workday Completes Acquisition of Paradox",
          "source_url": "https://www.prnewswire.com/news-releases/workday-completes-acquisition-of-paradox-302571738.html"
        },
        {
          "date": "2026-01-08",
          "headline": "Paradox Conversational Applicant Tracking System (ATS) Now Available Through Workday, Helping Organizations Hire Frontline Workers Faster",
          "source_url": "https://www.prnewswire.com/news-releases/paradox-conversational-applicant-tracking-system-ats-now-available-through-workday-helping-organizations-hire-frontline-workers-faster-302656477.html"
        }
      ],
      "growthSignals": [
        "Paradox achieved a 276% three-year growth rate as of its 2025 Inc. 5000 listing [Paradox Named to Fifth Consecutive Inc. 5000 List -- Among the Fastest Growing HR Technology Companies](https://www.prnewswire.com/news-releases/paradox-named-to-fifth-consecutive-inc-5000-list--among-the-fastest-growing-hr-technology-companies-302528360.html).",
        "Workday generated over $100 million in new annual contract value (ACV) from emerging AI products including Paradox in Q4 fiscal 2026 [Workday Stock Hits a Five-Year Low as $400 Million in AI ARR Goes Unnoticed | TIKR.com](https://www.tikr.com/blog/workday-stock-hits-a-five-year-low-as-400-million-in-ai-arr-goes-unnoticed).",
        "Paradox acquired people analytics platform Eqtble in 2024 to advance its AI vision [Conversational AI Leader Paradox Acquires People Analytics Platform Eqtble to Advance AI Vision — Paradox](https://www.paradox.ai/news/conversational-ai-leader-paradox-acquires-people-analytics-platform-eqtble-to-advance-ai-vision)."
      ],
      "top3Features": [
        "Olivia AI assistant",
        "Automated interview scheduling",
        "Conversational screening"
      ],
      "targetVerticals": [
        "Retail",
        "Restaurant",
        "Healthcare",
        "Logistics",
        "Manufacturing"
      ],
      "isSubject": false,
      "similarity": 0.78,
      "threat": "high",
      "pricing": {
        "model": "Custom",
        "starts_at": 0,
        "mention": "Contact sales"
      }
    },
    {
      "id": "harver",
      "name": "Harver",
      "domain": "",
      "tagline": "Better Talent Decisions. Faster. [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
      "category": "HR Technology [10 HR-Tech Terms You Should Know | Harver](https://harver.com/blog/hr-tech-terms/)",
      "subCategory": "AI pre-employment assessment software [New Harver and Greenhouse integration brings predictive assessment data to Greenhouse users | Harver](https://harver.com/press/harver-greenhouse-integration/)",
      "hq": "London [Harver - 2026 Company Profile, Team, Funding, Competitors & Financials - Tracxn](https://tracxn.com/d/companies/harver/__gjUW2iOTksxTBn3an7-rdB7W-NNpeKLIuWvPflf0-Gw), United Kingdom [Harver - 2026 Company Profile, Team, Funding, Competitors & Financials - Tracxn](https://tracxn.com/d/companies/harver/__gjUW2iOTksxTBn3an7-rdB7W-NNpeKLIuWvPflf0-Gw)",
      "hqCoords": [
        0.0,
        0.0
      ],
      "offices": [
        "London [Harver - 2026 Company Profile, Team, Funding, Competitors & Financials - Tracxn](https://tracxn.com/d/companies/harver/__gjUW2iOTksxTBn3an7-rdB7W-NNpeKLIuWvPflf0-Gw)"
      ],
      "founded": 2010,
      "employees": 175,
      "employeeGrowth": 0.0,
      "funding": {
        "total": 32200000.0,
        "lastRound": "Series B",
        "lastRoundAt": "2019-07-31",
        "status": "enriched",
        "rounds": [
          {
            "round": "Seed",
            "date": "2013-05-01",
            "amountEur": null
          },
          {
            "round": "Series A",
            "date": "2018-01-11",
            "amountEur": 3877793.56
          },
          {
            "round": "Series B",
            "date": "2019-07-31",
            "amountEur": 13800000.0
          }
        ],
        "totalRaisedEur": 32200000.0
      },
      "fundingRounds": [
        {
          "round": "Seed",
          "date": "2013-05-01",
          "amountEur": null
        },
        {
          "round": "Series A",
          "date": "2018-01-11",
          "amountEur": 3877793.56
        },
        {
          "round": "Series B",
          "date": "2019-07-31",
          "amountEur": 13800000.0
        }
      ],
      "fundingStage": "Acquired",
      "investors": [
        "Insight Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)",
        "Camden Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)",
        "Rubicon Technology Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)"
      ],
      "notable_investors": [
        {
          "name": "Insight Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)"
        },
        {
          "name": "Camden Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)"
        },
        {
          "name": "Rubicon Technology Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)"
        }
      ],
      "notable_customers": [
        {
          "name": "Arvato Bertelsmann",
          "segment": "Enterprise",
          "evidence": "Reduced unwanted employee turnover by 63% and increased selection rate from 45% to 85%. [Case Study - How Arvato reduced employee turnover by 63%](https://harver.com/wp-content/uploads/2019/03/harver_Arvato_Turnover.pdf)",
          "industry": "BPO"
        },
        {
          "name": "ADT",
          "segment": "Enterprise",
          "evidence": "Used predictive hiring to reduce attrition, save thousands of hours, and triple recruiter output. [Resources Archive | Harver](https://harver.com/resources/)",
          "industry": "Security & Smart Home Services"
        },
        {
          "name": "Paramount Advertising",
          "segment": "Enterprise",
          "evidence": "Increased workforce ethnic diversity by 254% and reduced attrition by 56%. [Exploring a Retail Hiring Case Study | Harver](https://harver.com/clients/retail/hema/)",
          "industry": "Tech, Media & Telecommunications"
        },
        {
          "name": "Valvoline",
          "segment": "Enterprise",
          "evidence": "Utilizes scientific approach to hiring to reduce recruitment time. [Harver's Assessment Solution: tools to identify top talent](https://harver.com/solutions/use-case/assessment-solution-software/)",
          "industry": "Automotive and Retail"
        },
        {
          "name": "GardaWorld Security – U.S.",
          "segment": "Enterprise",
          "evidence": "Elevated talent strategy by implementing 'The Right Fit, Right from the Start' program. [Clients Archive | Harver](https://harver.com/clients/)",
          "industry": "Security"
        }
      ],
      "key_people": [
        {
          "name": "Sean Barry",
          "role": "Chief Executive Officer (CEO)",
          "background": "Chief Executive Officer (CEO) at Harver, appointed in July 2025 to lead expansion. [Harver Appoints New CEO, Strengthens Executive Team to Help Customers Shape the Future of Hiring | Harver](https://harver.com/press/harver-appoints-new-ceo-strengthens-executive-team-to-help-customers-shape-the-future-of-hiring/)"
        },
        {
          "name": "Dr. Ben Porr",
          "role": "Chief Science Officer",
          "linkedin": "linkedin.com/in/benporr",
          "background": "Chief Science Officer at Harver, driving growth and loyalty with science-backed strategies. [Ben Porr - Chief Science Officer | I-O Psychologist | Driving Growth & Loyalty with Science-Backed Strategies | LinkedIn](https://www.linkedin.com/in/benporr/)"
        },
        {
          "name": "Rick Custodio",
          "role": "Chief Financial Officer (CFO)",
          "background": "Chief Financial Officer (CFO) at Harver. [About Harver: Transforming Talent Acquisition](https://harver.com/about-us/)"
        },
        {
          "name": "Tom Siegel",
          "role": "Chief Revenue Officer (CRO)",
          "background": "Chief Revenue Officer (CRO) at Harver. [About Harver: Transforming Talent Acquisition](https://harver.com/about-us/)"
        },
        {
          "name": "Arnold Sowole",
          "role": "Chief Product Officer (CPO)",
          "background": "Chief Product Officer (CPO) at Harver. [About Harver: Transforming Talent Acquisition](https://harver.com/about-us/)"
        }
      ],
      "customers": 1300,
      "arr": 134780000.0,
      "avgContract": null,
      "business_model": "B2B",
      "gtm_motion": "sales-led",
      "target_segment": "Enterprise",
      "geo_coverage": "Global",
      "acquisition": {
        "acquired": true,
        "acquirer": "Outmatch",
        "year": 2021,
        "sourceUrl": "https://camdenpartners.com/news/outmatch-and-harver-join-forces-to-create-the-worlds-leading-high-volume-hiring-solution"
      },
      "recentNews": [
        {
          "date": "2026-04-21",
          "headline": "Harver launched AI PREVAIL™",
          "source_url": "https://tracxn.com/d/companies/harver/__gjUW2iOTksxTBn3an7-rdB7W-NNpeKLIuWvPflf0-Gw"
        },
        {
          "date": "2025-07-15",
          "headline": "Harver appointed Sean Barry as CEO",
          "source_url": "https://harver.com/press/harver-appoints-new-ceo-strengthens-executive-team-to-help-customers-shape-the-future-of-hiring/"
        },
        {
          "date": "2025-04-03",
          "headline": "Harver featured in Universum Global regarding AI in recruitment",
          "source_url": "https://harver.com/newsroom/in-the-news/"
        },
        {
          "date": "2025-03-13",
          "headline": "Harver achieved Workday Certified Integration status",
          "source_url": "https://harver.com/newsroom/"
        },
        {
          "date": "2025-03-13",
          "headline": "Harver launched the Smart Job Navigator",
          "source_url": "https://tracxn.com/d/companies/harver/__gjUW2iOTksxTBn3an7-rdB7W-NNpeKLIuWvPflf0-Gw"
        }
      ],
      "growthSignals": [
        "Harver reached $146.5 million in revenue in June 2024. [How Harver hit $146.5M revenue with a 214 person team in 2024.](https://getlatka.com/companies/Harver)",
        "Harver acquired pymetrics in August 2022 to bolster its talent acquisition solutions. [Harver Acquires Pymetrics: One Team, One Mission | Harver](https://harver.com/harver-acquires-pymetrics/)",
        "Harver has been included on the Inc. 5000 list of fastest-growing private companies in the U.S. for two consecutive years. [Harver | LinkedIn](https://gt.linkedin.com/company/harver)"
      ],
      "top3Features": [
        "Predictive Assessments [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
        "Intelligent Automation [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
        "Video Interviewing [Video Interviewing Tips to Hire Smarter](https://harver.com/blog/video-interviewing-in-recruitment/)"
      ],
      "targetVerticals": [
        "BPO & Contact Centers [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
        "Retail [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
        "Tech, Media & Telecom [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
        "Financial Services & Insurance [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
        "Hospitality [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)"
      ],
      "isSubject": false,
      "similarity": 0.72,
      "threat": "medium",
      "pricing": {
        "model": "Custom",
        "starts_at": 0,
        "mention": "Contact sales"
      }
    }
  ],
  "features": [],
  "capabilities": {
    "maki_people": [],
    "basecamp": [],
    "stealth_co": [],
    "obscure_hr": [],
    "pending_co": []
  },
  "pricing": {
    "maki_people": [],
    "basecamp": [],
    "stealth_co": [],
    "obscure_hr": [],
    "pending_co": []
  },
  "funding": {
    "maki_people": [
      {
        "y": 2021,
        "q": 4,
        "amt": 6.0,
        "round": "Seed"
      },
      {
        "y": 2025,
        "q": 1,
        "amt": 27.8,
        "round": "Series A"
      }
    ],
    "basecamp": [],
    "stealth_co": [],
    "obscure_hr": [],
    "pending_co": []
  },
  "radar": {
    "axes": [
      "Breadth",
      "Depth",
      "Global",
      "Developer",
      "Pricing",
      "Trust"
    ],
    "scores": {
      "maki_people": [
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0
      ]
    },
    "defs": {
      "Breadth": "Breadth of product surface (modules, use-cases)",
      "Depth": "Depth within core payment workflows",
      "Global": "Geographic and currency coverage",
      "Developer": "API quality, docs, embedded SDKs",
      "Pricing": "Price-competitiveness for SMB/mid-market",
      "Trust": "Compliance, brand and customer logos"
    }
  }
};

window.RADAR_DATA.allCompanies = [
  {
    "id": "testgorilla",
    "name": "TestGorilla",
    "domain": "",
    "tagline": "Hire for real skills, IGNORE AI resumes. [TestGorilla: AI-Powered Talent Sourcing & Skills Assessments](https://www.testgorilla.com)",
    "category": "HR Technology",
    "subCategory": "Pre-employment testing software",
    "hq": "Amsterdam, Netherlands",
    "hqCoords": [
      52.3676,
      4.9041
    ],
    "offices": [
      "Amsterdam"
    ],
    "founded": 2020,
    "employees": 337,
    "employeeGrowth": 0.24,
    "funding": {
      "total": 74704000.0,
      "lastRound": "Series A",
      "lastRoundAt": "2022-06-13",
      "status": "enriched",
      "rounds": [
        {
          "round": "Pre-Seed",
          "date": "2020-01-01",
          "amountEur": 1104000.0
        },
        {
          "round": "Seed",
          "date": "2021-07-01",
          "amountEur": 9200000.0
        },
        {
          "round": "Series A",
          "date": "2022-06-13",
          "amountEur": 64400000.0
        }
      ],
      "totalRaisedEur": 74704000.0
    },
    "fundingRounds": [
      {
        "round": "Pre-Seed",
        "date": "2020-01-01",
        "amountEur": 1104000.0
      },
      {
        "round": "Seed",
        "date": "2021-07-01",
        "amountEur": 9200000.0
      },
      {
        "round": "Series A",
        "date": "2022-06-13",
        "amountEur": 64400000.0
      }
    ],
    "fundingStage": "Series A",
    "investors": [
      "Atomico",
      "Balderton Capital",
      "Notion Capital",
      "Partech",
      "Next Play Ventures"
    ],
    "notable_investors": [
      {
        "name": "Atomico"
      },
      {
        "name": "Balderton Capital"
      },
      {
        "name": "Notion Capital"
      },
      {
        "name": "Partech"
      },
      {
        "name": "Next Play Ventures"
      }
    ],
    "notable_customers": [
      {
        "name": "Dyninno Group",
        "segment": "Mixed",
        "evidence": "Increased recruitment productivity by 400% and screening efficiency by 4x using TestGorilla. [Dyninno Group improves candidate screening rate and increases recruitment productivity by 400% using TestGorilla](https://www.testgorilla.com/case-studies/dyninno-group-increases-recruitment-productivity-by-400-percent/)",
        "industry": "Travel, Finance, Entertainment, and Technology"
      },
      {
        "name": "Revolut",
        "segment": "Enterprise",
        "evidence": "Reported hiring 40% faster after implementing TestGorilla's assessment platform. [TestGorilla case studies - Helping companies hire the best talent](https://www.testgorilla.com/case-studies/revolut-improves-time-to-hire-by-40-using-testgorilla/)",
        "industry": "Financial Services"
      },
      {
        "name": "Penbrothers",
        "segment": "Enterprise",
        "evidence": "Used TestGorilla to reduce early attrition and improve candidate experience. [TestGorilla case studies - Helping companies hire the best talent](https://www.testgorilla.com/case-studies/penbrothers-humanises-global-hiring/)",
        "industry": "Global Talent Outsourcing"
      },
      {
        "name": "Orbit Technologies",
        "segment": "Enterprise",
        "evidence": "Improved new hire retention by 50% and reduced bias using TestGorilla. [TestGorilla case studies - Helping companies hire the best talent](https://www.testgorilla.com/case-studies/orbit-technologies-reduces-new-hire-attrition-rates/)",
        "industry": "Engineering"
      },
      {
        "name": "Lima Innovation Lab (LILAB)",
        "segment": "PME",
        "evidence": "Boosted new employee retention up to 90% using the platform. [TestGorilla case studies - Helping companies hire the best talent](https://www.testgorilla.com/case-studies/lilab-boost-new-employee-retention-up-to-90/)",
        "industry": "Software"
      }
    ],
    "key_people": [
      {
        "name": "Wouter Durville",
        "role": "CEO and Co-Founder",
        "linkedin": "linkedin.com/in/wouter-durville",
        "background": "CEO and Co-Founder of TestGorilla. [Wouter Durville](https://www.linkedin.com/in/wouter-durville)"
      },
      {
        "name": "Otto Verhage",
        "role": "COO and Co-Founder",
        "linkedin": "linkedin.com/in/otto-verhage",
        "background": "COO and Co-Founder of TestGorilla. [Otto Verhage - COO / Co-Founder at TestGorilla](https://nl.linkedin.com/in/otto-verhage)"
      },
      {
        "name": "Olive Turon",
        "role": "Head of People and Culture",
        "linkedin": "linkedin.com/in/olive-turon",
        "background": "Head of People and Culture at TestGorilla. [Olive Turon - LinkedIn](https://www.linkedin.com/in/olive-turon)"
      },
      {
        "name": "Megan Bourdages",
        "role": "VP of Sales",
        "linkedin": "linkedin.com/in/meganbourdages",
        "background": "VP of Sales at TestGorilla, leading the global sales organization. [Megan Bourdages - AMB International | LinkedIn](https://www.linkedin.com/in/meganbourdages/)"
      },
      {
        "name": "Romina da Costa",
        "role": "Product Director (IP Development)",
        "linkedin": "linkedin.com/in/rominadacosta",
        "background": "Product Director (IP Development) and Director of Talent and Assessment Science at TestGorilla. [Romina Da Costa - LinkedIn](https://www.linkedin.com/in/rominadacosta)"
      }
    ],
    "customers": 60000,
    "arr": 33304000.0,
    "avgContract": null,
    "business_model": "B2B",
    "gtm_motion": "product-led",
    "target_segment": "Mixed",
    "geo_coverage": "Global",
    "acquisition": {
      "acquired": false,
      "acquirer": null,
      "year": null,
      "sourceUrl": null
    },
    "recentNews": [
      {
        "date": "2026-05-06",
        "headline": "59% of Organizations Made a 'Bad AI Hire' in the Past Year, New TestGorilla Research Reveals",
        "source_url": "https://www.afp.com/en/infos/59-organizations-made-bad-ai-hire-past-year-new-testgorilla-research-reveals"
      },
      {
        "date": "2026-03-04",
        "headline": "TestGorilla launched a new suite of AI Readiness and AI Fluency assessments and simulation tests",
        "source_url": "https://tracxn.com/d/companies/testgorilla/__R2kvquwDSxYmt-AXwK9Qt8l_ReBLCwOIrxWBihbXqPo"
      },
      {
        "date": "2026-03-03",
        "headline": "TestGorilla Launches New AI Readiness and AI Fluency Assessments",
        "source_url": "https://lifestyle.pierrecountry.com/story/91873/testgorilla-launches-new-ai-readiness-and-ai-fluency-assessments-to-help-companies-hire-for-the-skills-that-matter-now/"
      },
      {
        "date": "2026-01-01",
        "headline": "TestGorilla launched five new simulation tests designed to mirror high-pressure scenarios for roles in Sales and Customer Success",
        "source_url": "https://support.testgorilla.com/hc/en-us/articles/46569751180699-Release-notes-December-2025-and-January-2026"
      },
      {
        "date": "2025-10-07",
        "headline": "TestGorilla introduced AI Video Interviews for skills-based screening",
        "source_url": "https://tracxn.com/d/companies/testgorilla/__R2kvquwDSxYmt-AXwK9Qt8l_ReBLCwOIrxWBihbXqPo"
      }
    ],
    "growthSignals": [
      "TestGorilla's revenue reached $36.2M ARR in 2025, with the company's valuation reported at $108.6M. [TestGorilla Revenue 2025: $36.2M ARR, $108.6M Valuation](https://getlatka.com/companies/testgorilla.com)",
      "As of March 2026, TestGorilla reports that more than 60,000 organizations use the platform, which assesses approximately 7 million candidates annually. [TestGorilla Launches New AI Readiness and AI Fluency Assessments - Morningstar](https://www.morningstar.com/news/business-wire/20260303398545/testgorilla-launches-new-ai-readiness-and-ai-fluency-assessments-to-help-companies-hire-for-the-skills-that-matter-now)",
      "TestGorilla grew its employee count by 24% last year. [TestGorilla: Revenue, Competitors, Alternatives](https://growjo.com/company/TestGorilla)"
    ],
    "top3Features": [
      "Library of 350+ scientifically validated skills tests",
      "AI video interviews with auto-scoring",
      "AI resume scoring against job descriptions"
    ],
    "targetVerticals": [
      "BPO",
      "Finance",
      "IT",
      "Sales"
    ],
    "isSubject": true,
    "similarity": 1.0,
    "threat": "high",
    "pricing": {
      "model": "Custom",
      "starts_at": 0,
      "mention": "Contact sales"
    }
  },
  {
    "id": "hirevue",
    "name": "HireVue",
    "domain": "hirevue.com",
    "tagline": "HireVue is where hiring happens.",
    "category": "HR Technology",
    "subCategory": "Hiring Platform",
    "hq": "Salt Lake City, United States",
    "hqCoords": [
      40.7608,
      -111.891
    ],
    "offices": [
      "Salt Lake City"
    ],
    "founded": 2004,
    "employees": 331,
    "employeeGrowth": 0.08,
    "funding": {
      "total": 85928000.0,
      "lastRound": "Series E",
      "lastRoundAt": "2015-06-02",
      "status": "enriched",
      "rounds": [
        {
          "round": "Series A",
          "date": "2008-02-10",
          "amountEur": 920000.0
        },
        {
          "round": "Series B",
          "date": "2010-07-27",
          "amountEur": 4600000.0
        },
        {
          "round": "Series E",
          "date": "2015-06-02",
          "amountEur": null
        }
      ],
      "totalRaisedEur": 85928000.0
    },
    "fundingRounds": [
      {
        "round": "Series A",
        "date": "2008-02-10",
        "amountEur": 920000.0
      },
      {
        "round": "Series B",
        "date": "2010-07-27",
        "amountEur": 4600000.0
      },
      {
        "round": "Series E",
        "date": "2015-06-02",
        "amountEur": null
      }
    ],
    "fundingStage": "Acquired",
    "investors": [
      "The Carlyle Group",
      "TCV",
      "Sequoia Capital",
      "Granite Ventures"
    ],
    "notable_investors": [
      {
        "name": "The Carlyle Group",
        "domain": "carlyle.com"
      },
      {
        "name": "TCV",
        "domain": "tcv.com"
      },
      {
        "name": "Sequoia Capital"
      },
      {
        "name": "Granite Ventures"
      }
    ],
    "notable_customers": [
      {
        "name": "Unilever",
        "domain": "unilever.com",
        "segment": "Enterprise",
        "evidence": "https://www.bestpractice.ai/ai-case-study-best-practice/unilever_saved_over_50,000_hours_in_candidate_interview_time_and_delivered_over_%C2%A31m_annual_savings_and_improved_candidate_diversity_with_machine_analysis_of_video-based_interviewing.",
        "industry": "Consumer Products"
      },
      {
        "name": "Delta Air Lines",
        "domain": "delta.com",
        "segment": "Enterprise",
        "evidence": "https://www.hirevue.com/case-studies/customer-videos/page/7",
        "industry": "Travel and Leisure"
      },
      {
        "name": "Walmart",
        "domain": "walmart.com",
        "segment": "Enterprise",
        "evidence": "https://www.hirevue.com/blog/hiring/high-volume-recruiting-success-case-studies",
        "industry": "Retail"
      },
      {
        "name": "IKEA",
        "domain": "ikea.com",
        "segment": "Enterprise",
        "evidence": "https://www.hirevue.com/case-studies",
        "industry": "Retail"
      },
      {
        "name": "Emirates NBD",
        "domain": "emiratesnbd.com",
        "segment": "Enterprise",
        "evidence": "https://www.hirevue.com/case-studies",
        "industry": "Banking"
      }
    ],
    "key_people": [
      {
        "name": "Jeremy Friedman",
        "background": "Chief Executive Officer (CEO) at HireVue, appointed in January 2024, recently leading the acquisition of Hireguide.",
        "current_role": "Chief Executive Officer (CEO)",
        "linkedin_url": "https://www.linkedin.com/in/jnfriedman"
      },
      {
        "name": "Alberto Silveira",
        "background": "Chief Technology Officer (CTO) at HireVue focused on breakthrough innovations and scaling product development.",
        "current_role": "Chief Technology Officer (CTO)",
        "linkedin_url": "https://www.linkedin.com/in/asilveira/"
      },
      {
        "name": "Walker Ellis",
        "background": "Chief Revenue Officer (CRO) at HireVue responsible for the company's revenue operations and strategic growth.",
        "current_role": "Chief Revenue Officer (CRO)",
        "linkedin_url": "https://www.linkedin.com/in/walker-ellis-26b20716/"
      },
      {
        "name": "Marcy Daniel",
        "background": "Chief Product Officer (CPO) at HireVue leading the product vision and development for the AI-driven talent platform.",
        "current_role": "Chief Product Officer (CPO)",
        "linkedin_url": "https://www.linkedin.com/in/marcyldaniel/"
      },
      {
        "name": "Sibyl McCarley",
        "background": "Chief People Officer at HireVue, having started the role on August 1, 2024.",
        "current_role": "Chief People Officer",
        "linkedin_url": "https://www.linkedin.com/in/sibyl-mccarley-7161543"
      }
    ],
    "customers": 1150,
    "arr": 76176000.0,
    "avgContract": 45866.6,
    "business_model": "B2B",
    "gtm_motion": "sales-led",
    "target_segment": "Enterprise",
    "geo_coverage": "Global",
    "acquisition": {
      "acquired": true,
      "acquirer": "The Carlyle Group",
      "year": 2019,
      "sourceUrl": "https://www.prnewswire.com/news-releases/hirevue-announces-close-of-transaction-with-the-carlyle-group-300937878.html"
    },
    "recentNews": [
      {
        "date": "2026-03-10",
        "headline": "HireVue announced the acquisition of the technology behind Hireguide",
        "source_url": "https://www.globenewswire.com/search/organization/Hirevue"
      },
      {
        "date": "2026-02-19",
        "headline": "HireVue launched 'Assessment Builder'",
        "source_url": "https://www.staffingindustry.com/news/global-daily-news/hirevue-acquires-hireguide"
      },
      {
        "date": "2026-01-13",
        "headline": "HireVue joined the Workday AI Agent Partner Network",
        "source_url": "https://www.hirevue.com/press-release"
      },
      {
        "date": "2025-10-08",
        "headline": "HireVue announced the launch of 'Interview Insights'",
        "source_url": "https://www.hirevue.com/press-release/hirevue-announces-interview-insights-expanding-its-innovation-in-skill-validation"
      },
      {
        "date": "2025-08-12",
        "headline": "HireVue launched 'Hirevue Talent Engagement'",
        "source_url": "https://www.globenewswire.com/search/organization/Hirevue"
      }
    ],
    "growthSignals": [
      "Acquired Hireguide in March 2026 to accelerate its AI strategy and strengthen conversational hiring technology.",
      "Joined the Workday AI Agent Partner Network in January 2026 to accelerate the shift toward skills-based hiring.",
      "Expanded its product suite with the launch of Assessment Builder and Interview Insights in late 2025 and early 2026."
    ],
    "top3Features": [
      "Video Interviewing",
      "Assessments",
      "Conversational AI"
    ],
    "targetVerticals": [
      "Retail",
      "Finance",
      "Software",
      "Pharmaceuticals",
      "Public Sector"
    ],
    "isSubject": false,
    "similarity": 0.84,
    "threat": "high",
    "pricing": {
      "model": "Custom",
      "starts_at": 0,
      "mention": "Contact sales"
    }
  },
  {
    "id": "paradox",
    "name": "Paradox",
    "domain": "",
    "tagline": "Conversational hiring software that gets work done for you. [Conversational hiring software that gets work done for you — Paradox](https://www.paradox.ai/)",
    "category": "HR Technology",
    "subCategory": "Conversational AI",
    "hq": "Scottsdale, US",
    "hqCoords": [
      33.4942,
      -111.9261
    ],
    "offices": [
      "Scottsdale"
    ],
    "founded": 2016,
    "employees": 429,
    "employeeGrowth": 0.0,
    "funding": {
      "total": 233183200.0,
      "lastRound": "Series C",
      "lastRoundAt": "2021-12-27",
      "status": "enriched",
      "rounds": [
        {
          "round": "Series A",
          "date": "2019-02-28",
          "amountEur": 12236000.0
        },
        {
          "round": "Series B",
          "date": "2020-05-11",
          "amountEur": 36800000.0
        },
        {
          "round": "Series C",
          "date": "2021-12-27",
          "amountEur": 184000000.0
        }
      ],
      "totalRaisedEur": 233183200.0
    },
    "fundingRounds": [
      {
        "round": "Series A",
        "date": "2019-02-28",
        "amountEur": 12236000.0
      },
      {
        "round": "Series B",
        "date": "2020-05-11",
        "amountEur": 36800000.0
      },
      {
        "round": "Series C",
        "date": "2021-12-27",
        "amountEur": 184000000.0
      }
    ],
    "fundingStage": "Acquired",
    "investors": [
      "Brighton Park Capital",
      "Stripes",
      "Sapphire Ventures",
      "Thoma Bravo",
      "Workday Ventures"
    ],
    "notable_investors": [
      {
        "name": "Brighton Park Capital"
      },
      {
        "name": "Stripes"
      },
      {
        "name": "Sapphire Ventures"
      },
      {
        "name": "Thoma Bravo"
      },
      {
        "name": "Workday Ventures"
      }
    ],
    "notable_customers": [
      {
        "name": "Compass Group",
        "segment": "Enterprise",
        "evidence": "Hiring 160,000 workers a year with a recruiting team of 20 [Hiring 160,000 workers a year with a recruiting team of 20.](https://www.paradox.ai/case-studies/compass-group)",
        "industry": "Food & Facilities"
      },
      {
        "name": "7-Eleven",
        "segment": "Enterprise",
        "evidence": "Uses Paradox to schedule 85% of applicants within the hour, saving store managers 40,000 hours per week [Paradox named to its fifth consecutive Inc. 5000 list — ranked as #X among HR technology companies. — Paradox](https://www.paradox.ai/news/paradox-named-to-its-fifth-consecutive-inc-5000-list-among-the-fastest-growing-hr-technology-companies).",
        "industry": "Retail"
      },
      {
        "name": "General Motors",
        "segment": "Enterprise",
        "evidence": "Saved more than $2 million in operational recruiting costs by leveraging Paradox automation [Paradox Named to Third Consecutive Inc. 5000 List — Growing by More than 720% Since 2020 — Paradox](https://www.paradox.ai/news/paradox-named-to-third-consecutive-inc-5000-list-growing-by-more-than-720-since-2020).",
        "industry": "Automotive"
      },
      {
        "name": "Sodexo",
        "segment": "Enterprise",
        "evidence": "Hired more than 40,000 people in seven months using Paradox's Conversational ATS [Decreasing time to hire by 60% with recruiting automation.](https://www.paradox.ai/case-studies/sodexo).",
        "industry": "Food & Facilities"
      },
      {
        "name": "Nestlé",
        "segment": "Enterprise",
        "evidence": "Utilizes Paradox to automate nearly 8,000 hours of recruiting work annually [Increasing interviews by 600% with recruiting automation.](https://www.paradox.ai/case-studies/nestle).",
        "industry": "Food & Beverage"
      }
    ],
    "key_people": [
      {
        "name": "Adam Godson",
        "role": "Chief Executive Officer",
        "linkedin": "linkedin.com/in/adamgodson",
        "background": "Adam Godson is the Chief Executive Officer (CEO) of Paradox and the General Manager of Paradox at Workday [Adam Godson - Workday | LinkedIn](https://www.linkedin.com/in/adamgodson/)."
      },
      {
        "name": "Stephanie King",
        "role": "Chief Legal Officer",
        "linkedin": "linkedin.com/in/stephanie-king-37346366",
        "background": "Stephanie King is the Chief Legal Officer at Paradox [Stephanie King - Chief Legal Officer](https://www.linkedin.com/in/stephanie-king-37346366/)."
      },
      {
        "name": "Alon Slutzky",
        "role": "VP of Engineering",
        "linkedin": "linkedin.com/in/slutzky",
        "background": "Alon Slutzky is the VP of Engineering at Paradox [Alon Slutzky - Workday | LinkedIn](https://www.linkedin.com/in/slutzky/)."
      },
      {
        "name": "Joshua Secrest",
        "role": "Vice President, Marketing & Client Advocacy",
        "linkedin": "linkedin.com/in/joshua-secrest-44b0042",
        "background": "Joshua Secrest is the Vice President, Marketing & Client Advocacy at Paradox [Joshua Secrest - Vice President, Marketing & Client Advocacy - Paradox | LinkedIn](https://www.linkedin.com/in/joshua-secrest-44b0042/)."
      },
      {
        "name": "Tri LE",
        "role": "VP & Head of Engineering, Vietnam",
        "linkedin": "linkedin.com/in/lehuutri",
        "background": "Tri LE is the VP & Head of Engineering, Vietnam at Paradox [Tri LE - VP & Head of Engineering, Vietnam - Paradox | LinkedIn](https://www.linkedin.com/in/lehuutri/?_l=en)."
      }
    ],
    "customers": null,
    "arr": 106536000.0,
    "avgContract": null,
    "business_model": "B2B",
    "gtm_motion": "sales-led",
    "target_segment": "Enterprise",
    "geo_coverage": "Global",
    "acquisition": {
      "acquired": true,
      "acquirer": "Workday",
      "year": 2025,
      "sourceUrl": "https://newsroom.workday.com/2025-10-01-Workday-Completes-Acquisition-of-Paradox"
    },
    "recentNews": [
      {
        "date": "2025-06-03",
        "headline": "Workday Announces New AI Agent Partner Network and Agent Gateway to Power the Next Generation of Human and Digital Workforces",
        "source_url": "https://newsroom.workday.com/2025-06-03-Workday-Announces-New-AI-Agent-Partner-Network-and-Agent-Gateway-to-Power-the-Next-Generation-of-Human-and-Digital-Workforces"
      },
      {
        "date": "2025-08-21",
        "headline": "Workday Signs Definitive Agreement to Acquire Paradox, the AI Company Redefining the Frontline Candidate Experience",
        "source_url": "https://www.prnewswire.com/news-releases/workday-signs-definitive-agreement-to-acquire-paradox-the-ai-company-redefining-the-frontline-candidate-experience-302536210.html"
      },
      {
        "date": "2025-08-01",
        "headline": "Paradox's New Immersive Job Preview Named 2025 Top HR Product of the Year by HR Executive",
        "source_url": "https://www.prnewswire.com/news-releases/paradoxs-new-immersive-job-preview-named-2025-top-hr-product-of-the-year-by-hr-executive-302526075.html"
      },
      {
        "date": "2025-10-01",
        "headline": "Workday Completes Acquisition of Paradox",
        "source_url": "https://www.prnewswire.com/news-releases/workday-completes-acquisition-of-paradox-302571738.html"
      },
      {
        "date": "2026-01-08",
        "headline": "Paradox Conversational Applicant Tracking System (ATS) Now Available Through Workday, Helping Organizations Hire Frontline Workers Faster",
        "source_url": "https://www.prnewswire.com/news-releases/paradox-conversational-applicant-tracking-system-ats-now-available-through-workday-helping-organizations-hire-frontline-workers-faster-302656477.html"
      }
    ],
    "growthSignals": [
      "Paradox achieved a 276% three-year growth rate as of its 2025 Inc. 5000 listing [Paradox Named to Fifth Consecutive Inc. 5000 List -- Among the Fastest Growing HR Technology Companies](https://www.prnewswire.com/news-releases/paradox-named-to-fifth-consecutive-inc-5000-list--among-the-fastest-growing-hr-technology-companies-302528360.html).",
      "Workday generated over $100 million in new annual contract value (ACV) from emerging AI products including Paradox in Q4 fiscal 2026 [Workday Stock Hits a Five-Year Low as $400 Million in AI ARR Goes Unnoticed | TIKR.com](https://www.tikr.com/blog/workday-stock-hits-a-five-year-low-as-400-million-in-ai-arr-goes-unnoticed).",
      "Paradox acquired people analytics platform Eqtble in 2024 to advance its AI vision [Conversational AI Leader Paradox Acquires People Analytics Platform Eqtble to Advance AI Vision — Paradox](https://www.paradox.ai/news/conversational-ai-leader-paradox-acquires-people-analytics-platform-eqtble-to-advance-ai-vision)."
    ],
    "top3Features": [
      "Olivia AI assistant",
      "Automated interview scheduling",
      "Conversational screening"
    ],
    "targetVerticals": [
      "Retail",
      "Restaurant",
      "Healthcare",
      "Logistics",
      "Manufacturing"
    ],
    "isSubject": false,
    "similarity": 0.78,
    "threat": "high",
    "pricing": {
      "model": "Custom",
      "starts_at": 0,
      "mention": "Contact sales"
    }
  },
  {
    "id": "harver",
    "name": "Harver",
    "domain": "",
    "tagline": "Better Talent Decisions. Faster. [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
    "category": "HR Technology [10 HR-Tech Terms You Should Know | Harver](https://harver.com/blog/hr-tech-terms/)",
    "subCategory": "AI pre-employment assessment software [New Harver and Greenhouse integration brings predictive assessment data to Greenhouse users | Harver](https://harver.com/press/harver-greenhouse-integration/)",
    "hq": "London [Harver - 2026 Company Profile, Team, Funding, Competitors & Financials - Tracxn](https://tracxn.com/d/companies/harver/__gjUW2iOTksxTBn3an7-rdB7W-NNpeKLIuWvPflf0-Gw), United Kingdom [Harver - 2026 Company Profile, Team, Funding, Competitors & Financials - Tracxn](https://tracxn.com/d/companies/harver/__gjUW2iOTksxTBn3an7-rdB7W-NNpeKLIuWvPflf0-Gw)",
    "hqCoords": [
      0.0,
      0.0
    ],
    "offices": [
      "London [Harver - 2026 Company Profile, Team, Funding, Competitors & Financials - Tracxn](https://tracxn.com/d/companies/harver/__gjUW2iOTksxTBn3an7-rdB7W-NNpeKLIuWvPflf0-Gw)"
    ],
    "founded": 2010,
    "employees": 175,
    "employeeGrowth": 0.0,
    "funding": {
      "total": 32200000.0,
      "lastRound": "Series B",
      "lastRoundAt": "2019-07-31",
      "status": "enriched",
      "rounds": [
        {
          "round": "Seed",
          "date": "2013-05-01",
          "amountEur": null
        },
        {
          "round": "Series A",
          "date": "2018-01-11",
          "amountEur": 3877793.56
        },
        {
          "round": "Series B",
          "date": "2019-07-31",
          "amountEur": 13800000.0
        }
      ],
      "totalRaisedEur": 32200000.0
    },
    "fundingRounds": [
      {
        "round": "Seed",
        "date": "2013-05-01",
        "amountEur": null
      },
      {
        "round": "Series A",
        "date": "2018-01-11",
        "amountEur": 3877793.56
      },
      {
        "round": "Series B",
        "date": "2019-07-31",
        "amountEur": 13800000.0
      }
    ],
    "fundingStage": "Acquired",
    "investors": [
      "Insight Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)",
      "Camden Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)",
      "Rubicon Technology Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)"
    ],
    "notable_investors": [
      {
        "name": "Insight Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)"
      },
      {
        "name": "Camden Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)"
      },
      {
        "name": "Rubicon Technology Partners [Outmatch rebrands as Harver to Lead Digital Transformation in Volume Hiring Globally | Camden Partners](https://camdenpartners.com/news/outmatch-rebrands-as-harver-to-lead-digital-transformation-in-volume-hiring-globally)"
      }
    ],
    "notable_customers": [
      {
        "name": "Arvato Bertelsmann",
        "segment": "Enterprise",
        "evidence": "Reduced unwanted employee turnover by 63% and increased selection rate from 45% to 85%. [Case Study - How Arvato reduced employee turnover by 63%](https://harver.com/wp-content/uploads/2019/03/harver_Arvato_Turnover.pdf)",
        "industry": "BPO"
      },
      {
        "name": "ADT",
        "segment": "Enterprise",
        "evidence": "Used predictive hiring to reduce attrition, save thousands of hours, and triple recruiter output. [Resources Archive | Harver](https://harver.com/resources/)",
        "industry": "Security & Smart Home Services"
      },
      {
        "name": "Paramount Advertising",
        "segment": "Enterprise",
        "evidence": "Increased workforce ethnic diversity by 254% and reduced attrition by 56%. [Exploring a Retail Hiring Case Study | Harver](https://harver.com/clients/retail/hema/)",
        "industry": "Tech, Media & Telecommunications"
      },
      {
        "name": "Valvoline",
        "segment": "Enterprise",
        "evidence": "Utilizes scientific approach to hiring to reduce recruitment time. [Harver's Assessment Solution: tools to identify top talent](https://harver.com/solutions/use-case/assessment-solution-software/)",
        "industry": "Automotive and Retail"
      },
      {
        "name": "GardaWorld Security – U.S.",
        "segment": "Enterprise",
        "evidence": "Elevated talent strategy by implementing 'The Right Fit, Right from the Start' program. [Clients Archive | Harver](https://harver.com/clients/)",
        "industry": "Security"
      }
    ],
    "key_people": [
      {
        "name": "Sean Barry",
        "role": "Chief Executive Officer (CEO)",
        "background": "Chief Executive Officer (CEO) at Harver, appointed in July 2025 to lead expansion. [Harver Appoints New CEO, Strengthens Executive Team to Help Customers Shape the Future of Hiring | Harver](https://harver.com/press/harver-appoints-new-ceo-strengthens-executive-team-to-help-customers-shape-the-future-of-hiring/)"
      },
      {
        "name": "Dr. Ben Porr",
        "role": "Chief Science Officer",
        "linkedin": "linkedin.com/in/benporr",
        "background": "Chief Science Officer at Harver, driving growth and loyalty with science-backed strategies. [Ben Porr - Chief Science Officer | I-O Psychologist | Driving Growth & Loyalty with Science-Backed Strategies | LinkedIn](https://www.linkedin.com/in/benporr/)"
      },
      {
        "name": "Rick Custodio",
        "role": "Chief Financial Officer (CFO)",
        "background": "Chief Financial Officer (CFO) at Harver. [About Harver: Transforming Talent Acquisition](https://harver.com/about-us/)"
      },
      {
        "name": "Tom Siegel",
        "role": "Chief Revenue Officer (CRO)",
        "background": "Chief Revenue Officer (CRO) at Harver. [About Harver: Transforming Talent Acquisition](https://harver.com/about-us/)"
      },
      {
        "name": "Arnold Sowole",
        "role": "Chief Product Officer (CPO)",
        "background": "Chief Product Officer (CPO) at Harver. [About Harver: Transforming Talent Acquisition](https://harver.com/about-us/)"
      }
    ],
    "customers": 1300,
    "arr": 134780000.0,
    "avgContract": null,
    "business_model": "B2B",
    "gtm_motion": "sales-led",
    "target_segment": "Enterprise",
    "geo_coverage": "Global",
    "acquisition": {
      "acquired": true,
      "acquirer": "Outmatch",
      "year": 2021,
      "sourceUrl": "https://camdenpartners.com/news/outmatch-and-harver-join-forces-to-create-the-worlds-leading-high-volume-hiring-solution"
    },
    "recentNews": [
      {
        "date": "2026-04-21",
        "headline": "Harver launched AI PREVAIL™",
        "source_url": "https://tracxn.com/d/companies/harver/__gjUW2iOTksxTBn3an7-rdB7W-NNpeKLIuWvPflf0-Gw"
      },
      {
        "date": "2025-07-15",
        "headline": "Harver appointed Sean Barry as CEO",
        "source_url": "https://harver.com/press/harver-appoints-new-ceo-strengthens-executive-team-to-help-customers-shape-the-future-of-hiring/"
      },
      {
        "date": "2025-04-03",
        "headline": "Harver featured in Universum Global regarding AI in recruitment",
        "source_url": "https://harver.com/newsroom/in-the-news/"
      },
      {
        "date": "2025-03-13",
        "headline": "Harver achieved Workday Certified Integration status",
        "source_url": "https://harver.com/newsroom/"
      },
      {
        "date": "2025-03-13",
        "headline": "Harver launched the Smart Job Navigator",
        "source_url": "https://tracxn.com/d/companies/harver/__gjUW2iOTksxTBn3an7-rdB7W-NNpeKLIuWvPflf0-Gw"
      }
    ],
    "growthSignals": [
      "Harver reached $146.5 million in revenue in June 2024. [How Harver hit $146.5M revenue with a 214 person team in 2024.](https://getlatka.com/companies/Harver)",
      "Harver acquired pymetrics in August 2022 to bolster its talent acquisition solutions. [Harver Acquires Pymetrics: One Team, One Mission | Harver](https://harver.com/harver-acquires-pymetrics/)",
      "Harver has been included on the Inc. 5000 list of fastest-growing private companies in the U.S. for two consecutive years. [Harver | LinkedIn](https://gt.linkedin.com/company/harver)"
    ],
    "top3Features": [
      "Predictive Assessments [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
      "Intelligent Automation [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
      "Video Interviewing [Video Interviewing Tips to Hire Smarter](https://harver.com/blog/video-interviewing-in-recruitment/)"
    ],
    "targetVerticals": [
      "BPO & Contact Centers [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
      "Retail [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
      "Tech, Media & Telecom [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
      "Financial Services & Insurance [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)",
      "Hospitality [Harver: Predictive Assessments and Automated Solutions](https://www.harver.com)"
    ],
    "isSubject": false,
    "similarity": 0.72,
    "threat": "medium",
    "pricing": {
      "model": "Custom",
      "starts_at": 0,
      "mention": "Contact sales"
    }
  }
];
