// Auto-generated by scripts/preview_understand.py — DO NOT EDIT
// Domain: makipeople.com — 2026-05-26T22:41:02.659567+00:00
window.RADAR_DATA = {
  "query": {
    "url": "makipeople.com",
    "name": "Maki People",
    "scannedAt": "2026-05-26T22:41:02.659567+00:00",
    "durationMs": 0,
    "sourcesScanned": 86
  },
  "subject": {
    "id": "maki_people",
    "name": "Maki People",
    "domain": "makipeople.com",
    "tagline": "Maki People provides AI-powered hiring software with autonomous agents that manage end-to-end recruitment workflows on top of existing ATS systems. The platform uses five AI agents (Shiro, Mochi, Ken, Kumi, Tomo) to handle intake, screening, assessment, interviews, and hire recommendations, delivering science-backed hiring decisions for Fortune 2000 enterprises.",
    "category": "HR Technology",
    "subCategory": "AI hiring intelligence platform with autonomous agents for enterprise recruitment",
    "hq": "Paris, France",
    "hqCoords": [
      48.8534951,
      2.3483915
    ],
    "offices": [
      "Paris"
    ],
    "founded": 2021,
    "employees": 122,
    "employeeGrowth": 0.0,
    "funding": {
      "total": 33800000.0,
      "lastRound": "Series A",
      "lastRoundAt": "2025-01-15"
    },
    "investors": [
      "Blossom Capital",
      "DST Global",
      "Frst Capital",
      "Global Founders Capital",
      "Picus Capital",
      "Secret Fund",
      "Kima Ventures",
      "Founders Future",
      "50 business angels"
    ],
    "pricing": {
      "model": "Custom",
      "startsAt": 0.0,
      "mention": "Contact sales"
    },
    "arr": null,
    "customers": 80,
    "avgContract": null,
    "notable": [
      "Raised €27.8M Series A in January 2025 led by Blossom Capital",
      "Hiring 60+ roles in 2025",
      "Expansion focus on U.S. market with CEO relocating to New York City",
      "Integrated with 30+ Applicant Tracking Systems",
      "Operating in 50+ global markets with 80% automation of screening and interviewing processes"
    ],
    "notable_customers": [
      {
        "name": "Deloitte",
        "domain": "deloitte.com",
        "segment": "Grand compte",
        "evidence": "Excellent support for the deployment of Maki, which helps the company quickly understand the candidate's profile - Melanie R., Director of Recruitment at Deloitte France"
      },
      {
        "name": "Nespresso",
        "domain": "nespresso.com",
        "segment": "Grand compte",
        "evidence": "49% reduction in turnover case study"
      },
      {
        "name": "Capgemini",
        "domain": "capgemini.com",
        "segment": "Grand compte",
        "evidence": "10 days time-to-hire reduction case study"
      },
      {
        "name": "Forvis Mazars",
        "domain": "forvismazars.com",
        "segment": "Grand compte",
        "evidence": "60% screening time reduction case study"
      },
      {
        "name": "H&M",
        "domain": "hm.com",
        "segment": "Grand compte",
        "evidence": "https://www.makipeople.com/"
      },
      {
        "name": "BNP Paribas",
        "domain": "bnpparibas.com",
        "segment": "Grand compte",
        "evidence": "https://www.makipeople.com/"
      },
      {
        "name": "EY",
        "domain": "ey.com",
        "segment": "Grand compte",
        "evidence": "https://www.linkedin.com/in/maximelegardez/"
      },
      {
        "name": "Amazon",
        "domain": "amazon.com",
        "segment": "Grand compte",
        "evidence": "https://www.linkedin.com/in/maximelegardez/"
      },
      {
        "name": "PwC",
        "domain": "pwc.com",
        "segment": "Grand compte",
        "evidence": "https://www.linkedin.com/in/maximelegardez/"
      },
      {
        "name": "Delta Airlines",
        "domain": "delta.com",
        "segment": "Grand compte",
        "evidence": "https://www.linkedin.com/in/maximelegardez/"
      },
      {
        "name": "BD",
        "domain": "bd.com",
        "segment": "Grand compte",
        "evidence": "https://www.linkedin.com/in/maximelegardez/"
      },
      {
        "name": "FIFA",
        "domain": "fifa.com",
        "segment": "Grand compte",
        "evidence": "https://www.linkedin.com/in/maximelegardez/"
      }
    ],
    "notable_investors": [
      {
        "name": "Blossom Capital",
        "domain": "blossomcap.com",
        "segment": null,
        "evidence": null
      },
      {
        "name": "DST Global",
        "domain": "dst.global",
        "segment": null,
        "evidence": null
      },
      {
        "name": "Frst Capital",
        "domain": null,
        "segment": null,
        "evidence": null
      },
      {
        "name": "Global Founders Capital",
        "domain": "globalfounders.vc",
        "segment": null,
        "evidence": null
      },
      {
        "name": "Picus Capital",
        "domain": "picuscap.com",
        "segment": null,
        "evidence": null
      },
      {
        "name": "Secret Fund",
        "domain": null,
        "segment": null,
        "evidence": null
      },
      {
        "name": "Kima Ventures",
        "domain": "kimaventures.com",
        "segment": null,
        "evidence": null
      },
      {
        "name": "Founders Future",
        "domain": null,
        "segment": null,
        "evidence": null
      },
      {
        "name": "50 business angels",
        "domain": null,
        "segment": null,
        "evidence": null
      }
    ],
    "key_people": [
      {
        "name": "Maxime Legardez Coquin",
        "role": "CEO & Co-founder",
        "linkedin": "https://www.linkedin.com/in/maximelegardez/",
        "background": "CEO and Co-founder of Maki People, previously worked at Rocket Internet and Sennder. A Forbes HR Council member, he's been featured in Forbes and TechCrunch for his work on AI-powered hiring."
      },
      {
        "name": "Benjamin Chino",
        "role": "CPO & Co-founder",
        "linkedin": "https://www.linkedin.com/in/benjamin-chino-39856617/",
        "background": "Co-founder and Chief Product Officer at Maki People, formerly VP Product at Sennder and global Product Operations lead for Uber for Business."
      },
      {
        "name": "Paul Louis Caylar",
        "role": "COO & Co-founder",
        "linkedin": "https://www.linkedin.com/in/paullouiscaylar/",
        "background": "Co-founder and Chief Operating Officer of Maki People, former McKinsey Partner. Under his leadership, Maki People has developed a comprehensive library of over 150 skills tests."
      },
      {
        "name": "Juliette Santelmo",
        "role": "Founder Associate",
        "linkedin": null,
        "background": "Founder Associate at Maki People, co-founded the company with Maxime Legardez Coquin and Marc Desazars."
      },
      {
        "name": "Marc Desazars",
        "role": "GTM & Strategy",
        "linkedin": "https://www.linkedin.com/in/marcdesazars/",
        "background": "GTM & Strategy at Maki People, formerly User Acquisition Associate at Voodoo and Digital Marketing Analyst at Groupe Marie Claire."
      }
    ],
    "isSubject": true,
    "similarity": null,
    "threat": null,
    "business_model": "B2B",
    "gtm_motion": "sales-led",
    "pricing_model_kind": "Usage-based",
    "target_segment": "Grand compte",
    "geo_coverage": "Global"
  },
  "competitors": [],
  "features": [],
  "capabilities": {
    "maki_people": []
  },
  "pricing": {
    "maki_people": []
  },
  "funding": {
    "maki_people": [
      {
        "y": 2021,
        "q": 4,
        "amt": 6.0,
        "round": "Seed"
      },
      {
        "y": 2025,
        "q": 1,
        "amt": 27.8,
        "round": "Series A"
      }
    ]
  },
  "radar": {
    "axes": [
      "Breadth",
      "Depth",
      "Global",
      "Developer",
      "Pricing",
      "Trust"
    ],
    "scores": {
      "maki_people": [
        50.0,
        50.0,
        50.0,
        50.0,
        50.0,
        50.0
      ]
    },
    "defs": {
      "Breadth": "Breadth of product surface (modules, use-cases)",
      "Depth": "Depth within core payment workflows",
      "Global": "Geographic and currency coverage",
      "Developer": "API quality, docs, embedded SDKs",
      "Pricing": "Price-competitiveness for SMB/mid-market",
      "Trust": "Compliance, brand and customer logos"
    }
  }
};
